var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
import { TouchableHighlight, View } from 'react-native';
import Feather from 'react-native-vector-icons/Feather';
export default {
    SignIn: {
        GetStarted: styled(View)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n      height: 160px;\n      width: 100%;\n      padding: 20px;\n      flex: 1;\n      background: #fff;\n    "], ["\n      height: 160px;\n      width: 100%;\n      padding: 20px;\n      flex: 1;\n      background: #fff;\n    "]))),
        PhoneInput: styled(View)(templateObject_2 || (templateObject_2 = __makeTemplateObject([""], [""]))),
        PhoneInputContent: styled(View)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n      background: #f8f8f8;\n      border: 1px solid #eee;\n      display: flex;\n      flex-direction: row;\n      align-items: center;\n      border-radius: 3px;\n      margin-top: 10px;\n      padding: 10px;\n    "], ["\n      background: #f8f8f8;\n      border: 1px solid #eee;\n      display: flex;\n      flex-direction: row;\n      align-items: center;\n      border-radius: 3px;\n      margin-top: 10px;\n      padding: 10px;\n    "]))),
        FlagAndPrefix: styled(TouchableHighlight)(templateObject_4 || (templateObject_4 = __makeTemplateObject([""], [""]))),
        FlagAndPrefixContent: styled(View)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n      display: flex;\n      flex: 6;\n      flex-direction: row;\n      align-items: center;\n      margin-right: 10px;\n    "], ["\n      display: flex;\n      flex: 6;\n      flex-direction: row;\n      align-items: center;\n      margin-right: 10px;\n    "]))),
        CountryArrow: styled(Feather)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n      font-size: 12px;\n      color: ", ";\n      margin-left: 3px;\n    "], ["\n      font-size: 12px;\n      color: ", ";\n      margin-left: 3px;\n    "])), function (props) { return props.theme.colors.gray; }),
        Header: styled(View)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n      width: 100%;\n      height: 100%;\n      padding: 78px 16px 48px 16px;\n      display: flex;\n      background: ", ";\n      flex-direction: column;\n    "], ["\n      width: 100%;\n      height: 100%;\n      padding: 78px 16px 48px 16px;\n      display: flex;\n      background: ", ";\n      flex-direction: column;\n    "])), function (props) { return props.theme.colors.blue; }),
        HeaderActionButton: styled(TouchableHighlight)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n      width: 48px;\n      height: 48px;\n      margin-left: 6px;\n      display: flex;\n      align-items: center;\n      justify-content: center;\n      flex-direction: row;\n    "], ["\n      width: 48px;\n      height: 48px;\n      margin-left: 6px;\n      display: flex;\n      align-items: center;\n      justify-content: center;\n      flex-direction: row;\n    "]))),
        LoginWithAnotherMethods: styled(TouchableHighlight)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n      height: 38px;\n      background: #fff;\n      display: flex;\n      margin-top: 15px;\n      flex-direction: row;\n      align-items: center;\n    "], ["\n      height: 38px;\n      background: #fff;\n      display: flex;\n      margin-top: 15px;\n      flex-direction: row;\n      align-items: center;\n    "]))),
        Logo: styled(Feather)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n      color: ", ";\n      font-size: 56px;\n    "], ["\n      color: ", ";\n      font-size: 56px;\n    "])), function (props) { return props.theme.colors.white; }),
        HeaderIcon: styled(Feather)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n      color: ", ";\n      font-size: 26px;\n    "], ["\n      color: ", ";\n      font-size: 26px;\n    "])), function (props) { return props.theme.colors.gray; }),
        Brand: styled(View)(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n      margin-left: 10px;\n    "], ["\n      margin-left: 10px;\n    "]))),
        PhoneInputDivider: styled(View)(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n      width: 1px;\n      height: 28px;\n      background: #ddd;\n    "], ["\n      width: 1px;\n      height: 28px;\n      background: #ddd;\n    "]))),
        Actions: styled(View)(templateObject_14 || (templateObject_14 = __makeTemplateObject(["\n      z-index: 2;\n      width: 100%;\n      left: 20px;\n      position: absolute;\n      bottom: 20px;\n      display: flex;\n      flex-direction: row;\n      align-items: center;\n      justify-content: space-between;\n    "], ["\n      z-index: 2;\n      width: 100%;\n      left: 20px;\n      position: absolute;\n      bottom: 20px;\n      display: flex;\n      flex-direction: row;\n      align-items: center;\n      justify-content: space-between;\n    "]))),
        NextButtonWrapper: styled(View)(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n      flex: 2;\n      display: flex;\n      flex-direction: row;\n      justify-content: flex-end;\n    "], ["\n      flex: 2;\n      display: flex;\n      flex-direction: row;\n      justify-content: flex-end;\n    "]))),
        NextButton: styled(TouchableHighlight)(templateObject_16 || (templateObject_16 = __makeTemplateObject(["\n      background: ", ";\n      width: 56px;\n      height: 56px;\n      border-radius: 28px;\n    "], ["\n      background: ", ";\n      width: 56px;\n      height: 56px;\n      border-radius: 28px;\n    "])), function (props) { return props.theme.colors.black; }),
        NextButtonInner: styled(View)(templateObject_17 || (templateObject_17 = __makeTemplateObject(["\n      width: 100%;\n      height: 100%;\n      display: flex;\n      align-items: center;\n      justify-content: center;\n    "], ["\n      width: 100%;\n      height: 100%;\n      display: flex;\n      align-items: center;\n      justify-content: center;\n    "]))),
        NextButtonIcon: styled(Feather)(templateObject_18 || (templateObject_18 = __makeTemplateObject(["\n      font-size: 22px;\n      color: ", ";\n    "], ["\n      font-size: 22px;\n      color: ", ";\n    "])), function (props) { return props.theme.colors.white; }),
    },
    SignInWithAnotherMethods: {
        Container: styled(View)(templateObject_19 || (templateObject_19 = __makeTemplateObject(["\n      height: 600px;\n      margin-left: -20px;\n      margin-right: -20px;\n      background: #fff;\n    "], ["\n      height: 600px;\n      margin-left: -20px;\n      margin-right: -20px;\n      background: #fff;\n    "]))),
        SignIn: styled(View)(templateObject_20 || (templateObject_20 = __makeTemplateObject(["\n      padding: 20px;\n    "], ["\n      padding: 20px;\n    "]))),
        SignUp: styled(View)(templateObject_21 || (templateObject_21 = __makeTemplateObject(["\n      padding: 20px;\n    "], ["\n      padding: 20px;\n    "]))),
        SocialButtons: styled(View)(templateObject_22 || (templateObject_22 = __makeTemplateObject(["\n      height: 100px;\n      padding: 20px;\n      background: #fff;\n    "], ["\n      height: 100px;\n      padding: 20px;\n      background: #fff;\n    "]))),
    },
    SocialButton: styled(TouchableHighlight)(templateObject_23 || (templateObject_23 = __makeTemplateObject(["\n    height: 48px;\n    width: 100%;\n  "], ["\n    height: 48px;\n    width: 100%;\n  "]))),
    SocialButtonContent: styled(View)(templateObject_24 || (templateObject_24 = __makeTemplateObject(["\n    height: 100%;\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    border-radius: 3px;\n    box-shadow: 0 0 3px #ddd;\n    background: #fff;\n    justify-content: center;\n    width: 100%;\n  "], ["\n    height: 100%;\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    border-radius: 3px;\n    box-shadow: 0 0 3px #ddd;\n    background: #fff;\n    justify-content: center;\n    width: 100%;\n  "]))),
    EmailPasswordSignInForm: styled(View)(templateObject_25 || (templateObject_25 = __makeTemplateObject(["\n    margin-top: 20px;\n  "], ["\n    margin-top: 20px;\n  "]))),
    EmailPasswordSignInFormItem: styled(View)(templateObject_26 || (templateObject_26 = __makeTemplateObject(["\n    margin: 10px 0;\n  "], ["\n    margin: 10px 0;\n  "]))),
    TermsAndPrivacy: styled(View)(templateObject_27 || (templateObject_27 = __makeTemplateObject(["\n    margin-top: 5px;\n    margin-bottom: 15px;\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    justify-content: center;\n  "], ["\n    margin-top: 5px;\n    margin-bottom: 15px;\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    justify-content: center;\n  "]))),
    EmailPasswordSignInButton: styled(TouchableHighlight)(templateObject_28 || (templateObject_28 = __makeTemplateObject(["\n    height: 48px;\n    width: 120px;\n    justify-content: center;\n    background: ", ";\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    border-radius: 3px;\n  "], ["\n    height: 48px;\n    width: 120px;\n    justify-content: center;\n    background: ", ";\n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    border-radius: 3px;\n  "])), function (props) { return props.theme.colors.blue; }),
};
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15, templateObject_16, templateObject_17, templateObject_18, templateObject_19, templateObject_20, templateObject_21, templateObject_22, templateObject_23, templateObject_24, templateObject_25, templateObject_26, templateObject_27, templateObject_28;
//# sourceMappingURL=Styled.js.map